// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';

export const REQUEST_SONGS = 'REQUEST_SONGS';
export const RECEIVE_SONGS = 'RECEIVE_SONGS';
export const ERROR_SONGS   = 'ERROR_SONGS';

export const REQUEST_SONG  = 'REQUEST_SONG';
export const RECEIVE_SONG  = 'RECEIVE_SONG';
export const ERROR_SONG    = 'ERROR_SONG';

export const REQUEST_SAVE_SONG = 'REQUEST_SAVE_SONG';
export const SUCCESS_SAVE_SONG = 'SUCCESS_SAVE_SONG';
export const ERROR_SAVE_SONG   = 'ERROR_SAVE_SONG';

export const REQUEST_UPDATE_SONG = 'REQUEST_UPDATE_SONG';
export const SUCCESS_UPDATE_SONG = 'SUCCESS_UPDATE_SONG';
export const ERROR_UPDATE_SONG   = 'ERROR_UPDATE_SONG';

export const REQUEST_DELETE_SONG = 'REQUEST_DELETE_SONG';
export const SUCCESS_DELETE_SONG = 'SUCCESS_DELETE_SONG';
export const ERROR_DELETE_SONG   = 'ERROR_DELETE_SONG';
