// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';

export const REQUEST_SONGS = 'REQUEST_SONGS';
export const RECEIVE_SONGS = 'RECEIVE_SONGS';
export const ERROR_SONGS   = 'ERROR_SONGS';

export const REQUEST_SONG  = 'REQUEST_SONG';
export const RECEIVE_SONG  = 'RECEIVE_SONG';
export const ERROR_SONG    = 'ERROR_SONG';

export const REQUEST_SAVE_SONG = 'REQUEST_SAVE_SONG';
export const SUCCESS_SAVE_SONG = 'SUCCESS_SAVE_SONG';
export const ERROR_SAVE_SONG   = 'ERROR_SAVE_SONG';

export const REQUEST_UPDATE_SONG = 'REQUEST_UPDATE_SONG';
export const SUCCESS_UPDATE_SONG = 'SUCCESS_UPDATE_SONG';
export const ERROR_UPDATE_SONG   = 'ERROR_UPDATE_SONG';

export const REQUEST_DELETE_SONG = 'REQUEST_DELETE_SONG';
export const SUCCESS_DELETE_SONG = 'SUCCESS_DELETE_SONG';
export const ERROR_DELETE_SONG   = 'ERROR_DELETE_SONG';

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const ERROR_CATEGORIES = 'ERROR_CATEGORIES';


export const REQUEST_ARTISTS = 'REQUEST_ARTISTS';
export const RECEIVE_ARTISTS = 'RECEIVE_ARTISTS';
export const ERROR_ARTISTS = 'ERROR_ARTISTS';


export const REQUEST_ALBUMS = 'REQUEST_ALBUMS';
export const RECEIVE_ALBUMS = 'RECEIVE_ALBUMS';
export const ERROR_ALBUMS = 'ERROR_ALBUMS';

export const REQUEST_CREATE_STREAM = 'REQUEST_CREATE_STREAM';
export const SUCCESS_CREATE_STREAM = 'SUCCESS_CREATE_STREAM';
export const ERROR_CREATE_STREAM = 'ERROR_CREATE_STREAM';

export const REQUEST_STREAM_COUNT = 'REQUEST_STREAM_COUNT';
export const RECEIVE_STREAM_COUNT = 'RECEIVE_STREAM_COUNT';